### PR TITLE
add sle15 box

### PR DESCRIPTION
**Pull request by denisok**
@jan--f @jschmid1  new box to test for SLE15

### CODE REVIEW

**Comment by jschmid1** [comment]
awesome, thanks @denisok

**Comment by denisok** [comment]
@jschmid1 if someone confirm that it is really SLE15 - I am OK to merge it...
Kiwi behavior was unexpected, so I don't know if that is a proper box.

**Comment by jschmid1** [comment]
@denisok checking

**Comment by jschmid1** [comment]
```
admin:~ # cat /etc/os-release
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
```

lgtm :+1:

**Comment by denisok** [comment]
I still don't believe it ) but fine - lets merge it.

**Pull request merged**
