### PR TITLE
Make setup always install newest Vagrant available

### PR DESCRIPTION
**Pull request by colder-is-better**
Figure out the version number of newest Vagrant, come up with the URL to the corresponding RPM, use that RPM with zypper

### CODE REVIEW

**Comment by jschmid1** [comment]
I'm not sure if that will work for everybody. IIRC we specifically tied this script to one version because it was the only version working with the libvirt plugin.

**Comment by colder-is-better** [comment]
For what it's worth, on my Leap 15.0 system I've been using Vagrant 2.2.4. I used the modified setup script to upgrade to the latest version of Vagrant, that would be 2.2.5, and I had no issues. The first time I did a "vagrant up" Vagrant complained and noted that I should update all plugins. I ran "vagrant plugin update" and since then I have no issues, no warnings -- everything seems to be working fine.

**Comment by jschmid1** [comment]
We maybe should re-enable the build-matrix. It'd super helpful for those kind of changes.

**Comment by denisok** [comment]
I think we should start using standard vagrant from the repo. I checked it for Tumbleweed it gets all needed dependencies and works.
We just need to check it for Leap 15.1 and remove all that custom install and build.

**Comment by mgfritch** [comment]
> I think we should start using standard vagrant from the repo. I checked it for Tumbleweed it gets all needed dependencies and works.
> We just need to check it for Leap 15.1 and remove all that custom install and build.

Agree, we should use the SUSE repos rather than pulling RPMs from elsewhere.

The official tumbleweed repo works well, but Leap 15.1 still requires use of RPMs from the dev. repo (https://build.opensuse.org/repositories/Virtualization:vagrant)

I have a similar solution, that might help for the case where `vagrant-libvirt` is not found in the official repositories: https://github.com/mgfritch/vagrant-ceph/commit/a057b4965ad2545c1403d9beff43f496578dd251

**Comment by denisok** [comment]
https://www.suse.com/c/vagrant-boxes-with-opensuse-tumbleweed-check-it-out/

**Comment by colder-is-better** [comment]
After some discussions I had with @denisok, I now have a new setup script for vagrant-ceph. I am closing this PR and will soon open a new one.

**Pull request closed without merging**
