### PR TITLE
Old version of vagrant RPM could no longer install boxes

### PR DESCRIPTION
**Pull request by tgeek77**

### CODE REVIEW

**Comment by tgeek77** [comment]
Here is the error with the previous version of vagrant:

==> data1: Box 'opensuse/openSUSE-42.3-x86_64' could not be found. Attempting to find and install...
    data1: Box Provider: libvirt
    data1: Box Version: >= 0
==> admin: Box 'opensuse/openSUSE-42.3-x86_64' could not be found. Attempting to find and install...
==> data1: An error occurred. The error will be shown after all tasks complete.
    admin: Box Provider: libvirt
    admin: Box Version: >= 0
==> admin: An error occurred. The error will be shown after all tasks complete.
==> mon1: Box 'opensuse/openSUSE-42.3-x86_64' could not be found. Attempting to find and install...
    mon1: Box Provider: libvirt
    mon1: Box Version: >= 0
==> mon1: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'mon1'
machine. Please handle this error then try again:

The box 'opensuse/openSUSE-42.3-x86_64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/opensuse/openSUSE-42.3-x86_64"]
Error: The requested URL returned error: 404 Not Found

An error occurred while executing the action on the 'data1'
machine. Please handle this error then try again:

The box 'opensuse/openSUSE-42.3-x86_64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/opensuse/openSUSE-42.3-x86_64"]
Error: The requested URL returned error: 404 Not Found

An error occurred while executing the action on the 'admin'
machine. Please handle this error then try again:

The box 'opensuse/openSUSE-42.3-x86_64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/opensuse/openSUSE-42.3-x86_64"]
Error: The requested URL returned error: 404 Not Found

-------

Vagrant boxes are no longer available on https://atlas.hashicorp.com/. They are now on https://app.vagrantup.com. The older version can't reach the new url.

**Comment by denisok** [comment]
yes, confirm that. That was changed really recently, as I have updated my boxes couple of days before.

```
$vagrant box update                                                     
==> admin: Checking for updates to 'opensuse/openSUSE-Tumbleweed-x86_64' 
    admin: Latest installed version: 1.0.4.20170929                      
    admin: Version constraints:                                          
    admin: Provider: libvirt                                             
There was an error while downloading the metadata for this box.          
The error message is shown below:                                        
                                                                         
The requested URL returned error: 404 Not Found                          
```

https://atlas.hashicorp.com/opensuse/openSUSE-42.3-x86_64:

>  The Packer, Artifact Registry and Terraform Enterprise (Legacy) features of Atlas will no longer be actively developed or maintained and will be fully decommissioned on Friday, March 30, 2018. Please see our guide on building immutable infrastructure with Packer on CI/CD for ideas on implementing Packer and Artifact Registry features yourself and the Upgrading From Terraform Enterprise (Legacy) guide to migrate to the new Terraform Enterprise.

**Comment by denisok** [comment]
@tgeek77 where is from vagrant 2.x download it now?

**Comment by tgeek77** [comment]
I downloaded it from: https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.rpm

**Comment by denisok** [comment]
@tgeek77 I mean from where vagrant downloads boxes now ? :)

**Comment by tgeek77** [comment]
With the updated Vagrant:

```
jsevans@cham:~/vagrant-ceph> vagrant up
Bringing machine 'mon1' up with 'libvirt' provider...
Bringing machine 'data1' up with 'libvirt' provider...
Bringing machine 'admin' up with 'libvirt' provider...
==> admin: Box 'opensuse/openSUSE-42.3-x86_64' could not be found. Attempting to find and install...
    admin: Box Provider: libvirt
    admin: Box Version: >= 0
==> admin: Loading metadata for box 'opensuse/openSUSE-42.3-x86_64'
    admin: URL: https://vagrantcloud.com/opensuse/openSUSE-42.3-x86_64
==> admin: Adding box 'opensuse/openSUSE-42.3-x86_64' (v1.0.5.20171128) for provider: libvirt
    admin: Downloading: https://vagrantcloud.com/opensuse/boxes/openSUSE-42.3-x86_64/versions/1.0.5.20171128/providers/libvirt.box
    admin: Progress: 1% (Rate: 1255k/s, Estimated time remaining: 0:12:25)^C==> admin: Waiting for cleanup before exiting...

```

**Comment by denisok** [comment]
I plan to reuse openSUSE boxes from here:
https://build.opensuse.org/project/show/home:jloehel:vagrant:images

like:
https://download.opensuse.org/repositories/home:/jloehel:/vagrant:/images/images_leap_42_3/leap-42.3.x86_64-libvirt.box

It is probably better as those image are build regularly and has all the updates in it. When vagrant cloud boxes are quite outdated.

@tgeek77 any objections about it ?

**Comment by denisok** [comment]
@tgeek77 I have updated it to 2.0.3 and looks like it works.

see:
https://github.com/openSUSE/vagrant-ceph/blob/master/openSUSE_vagrant_setup.sh

**Pull request closed without merging**
