### PR TITLE
adding openSUSE Leap 15 support

### PR DESCRIPTION
**Pull request by denisok**
add Leap 15 support as well as take BOX from local environment if defined.

### CODE REVIEW

**Comment by denisok** [comment]
http://storage-ci.suse.de:8080/job/vagrant-run-pr/10/

CI passed.
But what I need to change on CI is to actually use install script from the current dir, instead of master.

**Comment by jschmid1** [comment]
> But what I need to change on CI is to actually use install script from the current dir, instead of master.

I saw that happen with a PR that I can't find right now. Can you link it?

**Comment by jschmid1** [comment]
If the tests yield success, +1 from my side

**Comment by denisok** [comment]
@jschmid1 yes they passed.

I changed CI to run local install script here:
https://github.com/SUSE/sesci/pull/4

**Pull request merged**
